// Business Data Interface
export interface BusinessDataItem {
  Organization: string;
  Duration: string;
  Region: string;
  'Client Types': string;
  'Product name': string;
  'Insurer name': string;
  'Policy Type': string;
  'Bussiness Vertical': string;
  'LOB name': string;
  'No.of Policies': number;
  Premium: number;
  'Gross Premium': number;
  Revenue: number;
  'Revenue Percentage': number;
  Color: string;
}

// Business Data Export
export const businessData: BusinessDataItem[] = [
  {
    Organization: '',
    Duration: 'FY 2023-24',
    Region: 'Mumbai',
    'Client Types': 'Corporate',
    'Product name': 'Health Insurance',
    'Insurer name': 'ICICI Lombard',
    'Policy Type': 'Health Insurance',
    'Bussiness Vertical': 'Health Insurance',
    'LOB name': 'Employee Benefit',
    'No.of Policies': 3300,
    Premium: 120000000,
    'Gross Premium': 120000000,
    Revenue: 120000000,
    'Revenue Percentage': 11.29,
    Color: '#3B82F6',
  },
  {
    Organization: '',
    Duration: 'FY 2023-24',
    Region: 'Ahmedabad',
    'Client Types': 'Retail',
    'Product name': 'Professional Indemnity',
    'Insurer name': 'United India',
    'Policy Type': 'Directors & Officers Insurance',
    'Bussiness Vertical': 'Directors & Officers Insurance',
    'LOB name': 'Liability',
    'No.of Policies': 98235,
    Premium: 40000004,
    'Gross Premium': 40000004,
    Revenue: 40000004,
    'Revenue Percentage': 3.76,
    Color: '#EC4899',
  },
  {
    Organization: '',
    Duration: 'FY 2023-24',
    Region: 'Mumbai',
    'Client Types': 'Corporate',
    'Product name': 'Motor Insurance',
    'Insurer name': 'SBI',
    'Policy Type': 'Motor Insurance',
    'Bussiness Vertical': 'Motor Insurance',
    'LOB name': 'Property & Engineering',
    'No.of Policies': 1800,
    Premium: 1000000,
    'Gross Premium': 1000000,
    Revenue: 1000000,
    'Revenue Percentage': 0.09,
    Color: '#10B981',
  },
  {
    Organization: '',
    Duration: 'FY 2023-24',
    Region: 'Mumbai',
    'Client Types': 'Corporate',
    'Product name': 'Life Insurance',
    'Insurer name': 'ICICI Lombard',
    'Policy Type': 'Life Insurance',
    'Bussiness Vertical': 'Life Insurance',
    'LOB name': 'Marine',
    'No.of Policies': 2300,
    Premium: 20000000,
    'Gross Premium': 20000000,
    Revenue: 20000000,
    'Revenue Percentage': 1.88,
    Color: '#EF4444',
  },
  {
    Organization: '',
    Duration: 'FY 2023-24',
    Region: 'Delhi',
    'Client Types': 'Corporate',
    'Product name': 'Travel Insurance',
    'Insurer name': 'Reliance',
    'Policy Type': 'Travel Insurance',
    'Bussiness Vertical': 'Travel Insurance',
    'LOB name': 'Specie',
    'No.of Policies': 1300,
    Premium: 12000,
    'Gross Premium': 12000,
    Revenue: 12000,
    'Revenue Percentage': 0.0,
    Color: '#EC4899',
  },
  {
    Organization: '',
    Duration: 'FY 2023-24',
    Region: 'Banglore',
    'Client Types': 'Corporate',
    'Product name': 'Property Insurance',
    'Insurer name': 'HDFC ERGO',
    'Policy Type': 'Marine Insurance',
    'Bussiness Vertical': 'Marine Insurance',
    'LOB name': 'Specialities',
    'No.of Policies': 2340,
    Premium: 100000000,
    'Gross Premium': 100000000,
    Revenue: 100000000,
    'Revenue Percentage': 9.41,
    Color: '#10B981',
  },
  {
    Organization: '',
    Duration: 'FY 2023-24',
    Region: 'Chennai',
    'Client Types': 'Corporate',
    'Product name': 'Travel Insurance',
    'Insurer name': 'Bajaj Allianz',
    'Policy Type': 'Fire Insurance',
    'Bussiness Vertical': 'Fire Insurance',
    'LOB name': 'Liability',
    'No.of Policies': 111000,
    Premium: 90000000,
    'Gross Premium': 90000000,
    Revenue: 90000000,
    'Revenue Percentage': 8.47,
    Color: '#F59E0B',
  },
  {
    Organization: '',
    Duration: 'FY 2023-24',
    Region: 'Hyderabad',
    'Client Types': 'Corporate',
    'Product name': 'Marine Insurance',
    'Insurer name': 'Tata AIG',
    'Policy Type': 'Personal Accident Insurance',
    'Bussiness Vertical': 'Personal Accident Insurance',
    'LOB name': 'Aviation',
    'No.of Policies': 43120,
    Premium: 80000000,
    'Gross Premium': 80000000,
    Revenue: 80000000,
    'Revenue Percentage': 7.53,
    Color: '#8B5CF6',
  },
  {
    Organization: '',
    Duration: 'FY 2023-24',
    Region: 'Hyderabad',
    'Client Types': 'Corporate',
    'Product name': 'Cyber Insurance',
    'Insurer name': 'New India',
    'Policy Type': 'Professional Indemnity Insurance',
    'Bussiness Vertical': 'Professional Indemnity Insurance',
    'LOB name': 'Liability',
    'No.of Policies': 4343,
    Premium: 70000001,
    'Gross Premium': 70000001,
    Revenue: 70000001,
    'Revenue Percentage': 6.59,
    Color: '#EF4444',
  },
  {
    Organization: '',
    Duration: 'FY 2023-24',
    Region: 'Hyderabad',
    'Client Types': 'Corporate',
    'Product name': 'Pet Insurance',
    'Insurer name': 'Oriental',
    'Policy Type': 'Public Liability Insurance',
    'Bussiness Vertical': 'Public Liability Insurance',
    'LOB name': 'Liability',
    'No.of Policies': 383800,
    Premium: 60000002,
    'Gross Premium': 60000002,
    Revenue: 60000002,
    'Revenue Percentage': 5.65,
    Color: '#06B6D4',
  },
  {
    Organization: '',
    Duration: 'FY 2023-24',
    Region: 'kolkata',
    'Client Types': 'Corporate',
    'Product name': 'Business Insurance',
    'Insurer name': 'Reliance',
    'Policy Type': 'Product Liability Insurance',
    'Bussiness Vertical': 'Product Liability Insurance',
    'LOB name': 'Liability',
    'No.of Policies': 45765,
    Premium: 50000003,
    'Gross Premium': 50000003,
    Revenue: 50000003,
    'Revenue Percentage': 4.7,
    Color: '#84CC16',
  },
  {
    Organization: '',
    Duration: 'FY 2023-24',
    Region: 'Pune',
    'Client Types': 'Retail',
    'Product name': 'Home Insurance',
    'Insurer name': 'National Insurance',
    'Policy Type': 'Employment Practices Liability',
    'Bussiness Vertical': 'Employment Practices Liability',
    'LOB name': 'Liability',
    'No.of Policies': 78123,
    Premium: 30000005,
    'Gross Premium': 30000005,
    Revenue: 30000005,
    'Revenue Percentage': 2.82,
    Color: '#14B8A6',
  },
  {
    Organization: '',
    Duration: 'FY 2023-24',
    Region: 'Delhi',
    'Client Types': 'Retail',
    'Product name': 'Credit Insurance',
    'Insurer name': 'SBI',
    'Policy Type': 'Cyber Liability Insurance',
    'Bussiness Vertical': 'Cyber Liability Insurance',
    'LOB name': 'Liability',
    'No.of Policies': 763265,
    Premium: 30000006,
    'Gross Premium': 30000006,
    Revenue: 30000006,
    'Revenue Percentage': 2.82,
    Color: '#F97316',
  },
  {
    Organization: '',
    Duration: 'FY 2023-24',
    Region: 'Banglore',
    'Client Types': 'Retail',
    'Product name': 'Liability Insurance',
    'Insurer name': 'Future Generali',
    'Policy Type': 'Key Person Insurance',
    'Bussiness Vertical': 'Key Person Insurance',
    'LOB name': 'Professional Indemnity',
    'No.of Policies': 348798,
    Premium: 20000007,
    'Gross Premium': 20000007,
    Revenue: 20000007,
    'Revenue Percentage': 1.88,
    Color: '#EC4899',
  },
  {
    Organization: '',
    Duration: 'FY 2023-24',
    Region: 'Banglore',
    'Client Types': 'Affinity',
    'Product name': 'Agriculture Insurance',
    'Insurer name': 'Liberty',
    'Policy Type': 'Business Interruption Insurance',
    'Bussiness Vertical': 'Business Interruption Insurance',
    'LOB name': 'Product Recall',
    'No.of Policies': 665229,
    Premium: 10000008,
    'Gross Premium': 10000008,
    Revenue: 10000008,
    'Revenue Percentage': 0.94,
    Color: '#14B8A6',
  },
  {
    Organization: '',
    Duration: 'FY 2023-24',
    Region: 'Banglore',
    'Client Types': 'Affinity',
    'Product name': 'Aviation Insurance',
    'Insurer name': 'IFFCO Tokio',
    'Policy Type': 'Equipment Insurance',
    'Bussiness Vertical': 'Equipment Insurance',
    'LOB name': 'Environmental',
    'No.of Policies': 98123,
    Premium: 1000009,
    'Gross Premium': 1000009,
    Revenue: 1000009,
    'Revenue Percentage': 0.09,
    Color: '#F97316',
  },
  {
    Organization: '',
    Duration: 'FY 2023-24',
    Region: 'kolkata',
    'Client Types': 'Affinity',
    'Product name': 'Workers Compensation',
    'Insurer name': 'Cholamandalam MS',
    'Policy Type': 'Cargo Insurance',
    'Bussiness Vertical': 'Cargo Insurance',
    'LOB name': 'LOB name',
    'No.of Policies': 90022,
    Premium: 900010,
    'Gross Premium': 900010,
    Revenue: 900010,
    'Revenue Percentage': 0.08,
    Color: '#FF6B6B',
  },
  {
    Organization: '',
    Duration: 'FY 2023-24',
    Region: 'Ahmedabad',
    'Client Types': 'Affinity',
    'Product name': 'Health Insurance',
    'Insurer name': 'Royal Sundaram',
    'Policy Type': 'Credit Insurance',
    'Bussiness Vertical': 'Credit Insurance',
    'LOB name': 'Employee Benefit',
    'No.of Policies': 34588,
    Premium: 800011,
    'Gross Premium': 800011,
    Revenue: 800011,
    'Revenue Percentage': 0.08,
    Color: '#4ECDC4',
  },
  {
    Organization: '',
    Duration: 'FY 2022-23',
    Region: 'Pune',
    'Client Types': 'Affinity',
    'Product name': 'Motor Insurance',
    'Insurer name': 'ICICI Lombard',
    'Policy Type': 'Fidelity Guarantee Insurance',
    'Bussiness Vertical': 'Fidelity Guarantee Insurance',
    'LOB name': 'Property & Engineering',
    'No.of Policies': 1170,
    Premium: 10800,
    'Gross Premium': 10800,
    Revenue: 10800,
    'Revenue Percentage': 0.0,
    Color: '#3B82F6',
  },
  {
    Organization: '',
    Duration: 'FY 2022-23',
    Region: 'Delhi',
    'Client Types': 'Affinity',
    'Product name': 'Life Insurance',
    'Insurer name': 'HDFC ERGO',
    'Policy Type': 'Workmen Compensation Insurance',
    'Bussiness Vertical': 'Workmen Compensation Insurance',
    'LOB name': 'Marine',
    'No.of Policies': 2106,
    Premium: 90000000,
    'Gross Premium': 90000000,
    Revenue: 90000000,
    'Revenue Percentage': 14.23,
    Color: '#10B981',
  },
  {
    Organization: '',
    Duration: 'FY 2022-23',
    Region: 'Mumbai',
    'Client Types': 'Affinity',
    'Product name': 'Travel Insurance',
    'Insurer name': 'Bajaj Allianz',
    'Policy Type': 'Group Personal Accident',
    'Bussiness Vertical': 'Group Personal Accident',
    'LOB name': 'Specie',
    'No.of Policies': 99900,
    Premium: 81000000,
    'Gross Premium': 81000000,
    Revenue: 81000000,
    'Revenue Percentage': 12.81,
    Color: '#F59E0B',
  },
  {
    Organization: '',
    Duration: 'FY 2022-23',
    Region: 'Mumbai',
    'Client Types': 'Affinity',
    'Product name': 'Property Insurance',
    'Insurer name': 'Tata AIG',
    'Policy Type': 'Group Health Insurance',
    'Bussiness Vertical': 'Group Health Insurance',
    'LOB name': 'Specialities',
    'No.of Policies': 38808,
    Premium: 72000000,
    'Gross Premium': 72000000,
    Revenue: 72000000,
    'Revenue Percentage': 11.38,
    Color: '#8B5CF6',
  },
  {
    Organization: '',
    Duration: 'FY 2022-23',
    Region: 'Mumbai',
    'Client Types': 'Retail',
    'Product name': 'Travel Insurance',
    'Insurer name': 'New India',
    'Policy Type': 'Term Life Insurance',
    'Bussiness Vertical': 'Term Life Insurance',
    'LOB name': 'Liability',
    'No.of Policies': 3908.7,
    Premium: 63000000.9,
    'Gross Premium': 63000000.9,
    Revenue: 63000000.9,
    'Revenue Percentage': 9.96,
    Color: '#EF4444',
  },
  {
    Organization: '',
    Duration: 'FY 2022-23',
    Region: 'Delhi',
    'Client Types': 'Retail',
    'Product name': 'Marine Insurance',
    'Insurer name': 'Oriental',
    'Policy Type': 'Whole Life Insurance',
    'Bussiness Vertical': 'Whole Life Insurance',
    'LOB name': 'Liability',
    'No.of Policies': 345420,
    Premium: 54000001.8,
    'Gross Premium': 54000001.8,
    Revenue: 54000001.8,
    'Revenue Percentage': 8.54,
    Color: '#06B6D4',
  },
  {
    Organization: '',
    Duration: 'FY 2022-23',
    Region: 'Banglore',
    'Client Types': 'Affinity',
    'Product name': 'Cyber Insurance',
    'Insurer name': 'Reliance',
    'Policy Type': 'Directors & Officers Insurance',
    'Bussiness Vertical': 'Directors & Officers Insurance',
    'LOB name': 'Liability',
    'No.of Policies': 41188.5,
    Premium: 45000002.7,
    'Gross Premium': 45000002.7,
    Revenue: 45000002.7,
    'Revenue Percentage': 7.12,
    Color: '#84CC16',
  },
  {
    Organization: '',
    Duration: 'FY 2022-23',
    Region: 'Chennai',
    'Client Types': 'Affinity',
    'Product name': 'Pet Insurance',
    'Insurer name': 'United India',
    'Policy Type': 'Employment Practices Liability',
    'Bussiness Vertical': 'Employment Practices Liability',
    'LOB name': 'Liability',
    'No.of Policies': 88411.5,
    Premium: 36000003.6,
    'Gross Premium': 36000003.6,
    Revenue: 36000003.6,
    'Revenue Percentage': 5.69,
    Color: '#EC4899',
  },
  {
    Organization: '',
    Duration: 'FY 2022-23',
    Region: 'Hyderabad',
    'Client Types': 'Affinity',
    'Product name': 'Business Insurance',
    'Insurer name': 'National Insurance',
    'Policy Type': 'Cyber Liability Insurance',
    'Bussiness Vertical': 'Cyber Liability Insurance',
    'LOB name': 'Liability',
    'No.of Policies': 70310.7,
    Premium: 27000004.5,
    'Gross Premium': 27000004.5,
    Revenue: 27000004.5,
    'Revenue Percentage': 4.27,
    Color: '#14B8A6',
  },
  {
    Organization: '',
    Duration: 'FY 2022-23',
    Region: 'Hyderabad',
    'Client Types': 'Affinity',
    'Product name': 'Professional Indemnity',
    'Insurer name': 'SBI',
    'Policy Type': 'Key Person Insurance',
    'Bussiness Vertical': 'Key Person Insurance',
    'LOB name': 'Liability',
    'No.of Policies': 686938.5,
    Premium: 27000005.4,
    'Gross Premium': 27000005.4,
    Revenue: 27000005.4,
    'Revenue Percentage': 4.27,
    Color: '#F97316',
  },
  {
    Organization: '',
    Duration: 'FY 2022-23',
    Region: 'Hyderabad',
    'Client Types': 'Corporate',
    'Product name': 'Home Insurance',
    'Insurer name': 'Future Generali',
    'Policy Type': 'Business Interruption Insurance',
    'Bussiness Vertical': 'Business Interruption Insurance',
    'LOB name': 'Liability',
    'No.of Policies': 313918.2,
    Premium: 18000006.3,
    'Gross Premium': 18000006.3,
    Revenue: 18000006.3,
    'Revenue Percentage': 2.85,
    Color: '#EC4899',
  },
  {
    Organization: '',
    Duration: 'FY 2022-23',
    Region: 'kolkata',
    'Client Types': 'Corporate',
    'Product name': 'Credit Insurance',
    'Insurer name': 'Liberty',
    'Policy Type': 'Equipment Insurance',
    'Bussiness Vertical': 'Equipment Insurance',
    'LOB name': 'Liability',
    'No.of Policies': 598706.1,
    Premium: 9000007.2,
    'Gross Premium': 9000007.2,
    Revenue: 9000007.2,
    'Revenue Percentage': 1.42,
    Color: '#14B8A6',
  },
  {
    Organization: '',
    Duration: 'FY 2022-23',
    Region: 'Banglore',
    'Client Types': 'Corporate',
    'Product name': 'Liability Insurance',
    'Insurer name': 'IFFCO Tokio',
    'Policy Type': 'Cargo Insurance',
    'Bussiness Vertical': 'Cargo Insurance',
    'LOB name': 'Professional Indemnity',
    'No.of Policies': 88310.7,
    Premium: 900008.1,
    'Gross Premium': 900008.1,
    Revenue: 900008.1,
    'Revenue Percentage': 0.14,
    Color: '#F97316',
  },
  {
    Organization: '',
    Duration: 'FY 2022-23',
    Region: 'Chennai',
    'Client Types': 'Corporate',
    'Product name': 'Agriculture Insurance',
    'Insurer name': 'Cholamandalam MS',
    'Policy Type': 'Credit Insurance',
    'Bussiness Vertical': 'Credit Insurance',
    'LOB name': 'Product Recall',
    'No.of Policies': 81019.8,
    Premium: 810009,
    'Gross Premium': 810009,
    Revenue: 810009,
    'Revenue Percentage': 0.13,
    Color: '#FF6B6B',
  },
  {
    Organization: '',
    Duration: 'FY 2022-23',
    Region: 'Hyderabad',
    'Client Types': 'Corporate',
    'Product name': 'Aviation Insurance',
    'Insurer name': 'Royal Sundaram',
    'Policy Type': 'Fidelity Guarantee Insurance',
    'Bussiness Vertical': 'Fidelity Guarantee Insurance',
    'LOB name': 'Environmental',
    'No.of Policies': 31129.2,
    Premium: 720009.9,
    'Gross Premium': 720009.9,
    Revenue: 720009.9,
    'Revenue Percentage': 0.11,
    Color: '#4ECDC4',
  },
];
